name: Update K8s Manifest

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  update-k8s-manifest:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Update image tag
        run: |
          sed -i "s|image: yevhent/python-test-server:.*|image: yevhent/python-test-server:${{ github.sha }}|" manifests/deployment.yaml
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git commit -am "Update image tag to ${{ github.sha }}"
          git push